script: cp "website/Användbara bilder/Mobil.html" "website/Användbara bilder/index.html"

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: 'Användbara bilder'
    on:
        branch: master
